<a href="https://colab.research.google.com/github/cristianmejia00/clustering/blob/main/Topic_Models_using_BERTopic_TOPIC_MODEL_20241101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Topic Modeling with BERTopic

This notebook runs BERTopic topic modeling on a prepared bibliometric corpus.

**Pipeline position:**
1. Dataset preparation (R pipeline)
2. Embedding generation (EMBEDS notebook or `pipelines/dataset/build_embeddings.py`)
3. Topic modeling (this notebook)
4. Topic diagnostics and reporting

**What this notebook expects:**
- A valid analysis profile (for example `a01`) with its settings JSON
- Precomputed embedding artifacts from the selected embedding profile (for example `e01`)
- Dataset artifacts generated by the dataset pipeline

**What this notebook does:**
1. Loads analysis settings
2. Loads dataset corpus and embeddings
3. Runs UMAP + clustering + BERTopic fitting
4. Produces topic tables and visual diagnostics

**Notes:**
- This notebook is intended to consume artifacts rather than recompute embeddings.
- For consistency, keep analysis and embedding profile names aligned with `config_analysis.yml` and `config_dataset.yml`.

## Requirements and Setup

### Imports and package initialization

In [32]:
import pandas as pd
import os
import json
import numpy as np
from datetime import date
from itertools import compress
from pathlib import Path
import yaml
from bertopic import BERTopic
from umap import UMAP
from sklearn.cluster import KMeans

## Inputs and Options

This section defines runtime paths and profile identifiers from YAML configuration files only.

**Path source policy:**
- Use configuration files only (`config_dataset.yml` and `config_analysis.yml`)
- Do not rely on environment variables

**Expected inputs:**
- Existing embeddings and corpus artifacts for the profile referenced in analysis settings

If artifacts are missing, run the dataset pipeline and embeddings pipeline first.

In [33]:
# Load configuration from YAML files
with open("../../../config_dataset.yml", "r") as f:
    dataset_config = yaml.safe_load(f)

with open("../../../config_analysis.yml", "r") as f:
    settings = yaml.safe_load(f)

# Backward-compatible alias for notebooks expecting old key names
if "tmo" not in settings and "topic_model" in settings:
    settings["tmo"] = settings["topic_model"]

ROOT_FOLDER_PATH = str(Path(settings["metadata"]["bibliometrics_directory"]))
project_folder = settings["metadata"]["project_folder"]
analysis_id = settings["metadata"]["analysis_id"]

In [34]:
# Settings are already loaded from config_analysis.yml in the previous cell

In [35]:
# Input dataset
dataset_file_path = f"{ROOT_FOLDER_PATH}/{settings['metadata']['project_folder']}/{settings['metadata']['filtered_folder']}/dataset_raw_cleaned.csv"

In [36]:
# Function to save files
def save_as_csv(df, save_name_without_extension, with_index):
    "usage: `save_as_csv(dataframe, 'filename')`"
    df.to_csv(f"{ROOT_FOLDER_PATH}/{save_name_without_extension}.csv", index=with_index)
    print("===\nSaved: ", f"{ROOT_FOLDER_PATH}/{save_name_without_extension}.csv")

In [37]:
# Open the data file
df = pd.read_csv(f"{dataset_file_path}", encoding='latin-1', usecols=['X_N', 'uuid', 'UT', 'PY', 'TI', 'AB'])
print(df.shape)
df.head()

(2801, 6)

,X_N,uuid,UT,TI,AB,PY
0,1,07f20478-d824-4671-bb1d-63d4a752a7e9,2-s2.0-84949158352,T2 Transfer of High Technology from the United...,The Union of Soviet Socialist Republics and th...,1984
1,2,59bd7b4e-3c82-4060-8750-a1af76080fa5,2-s2.0-105032555991,"""""As if geology ended at the seashore"""": Tempo...","Places of passage, diplomatic disputes, meetin...",2024
2,3,9cc08b63-2503-4c60-b324-8ebc3526e0d9,2-s2.0-105004398893,"""""Discrepant Expectation"""": The Delegation of ...",Prior to the reestablishment of diplomatic rel...,2024
3,4,f82beb11-5534-4283-ae79-60992a237a2a,2-s2.0-79960832417,"""""Let the devil do the rest"""": The promotion o...","During the 1940s, the United States undertook ...",2011
4,5,2364b8d6-26be-49c0-976d-0f880ff7e2c5,WOS:000207923100006,"'A Game, a Competition, an Instrument?': High ...",International sporting events such as the Olym...,2009



---

## PART 2: Topic Model

In [38]:
# bibliometrics_folder
# project_folder
# project_name_suffix
# ROOT_FOLDER_PATH = f"drive/MyDrive/{bibliometrics_folder}"

#############################################################
# Embeddings folder
embeddings_folder_name = settings['tmo']['embeds_folder']

# Which column has the year of the documents?
my_year = settings['tmo']['year_column']

# Number of topics. Select the number of topics to extract.
# Choose 0, for automatic detection.
n_topics = 71#settings['tmo']['n_topics']

# Minimum number of documents per topic
min_topic_size = settings['tmo']['min_topic_size']

# Threshold for others
# This is the threshold for the topics that will be considered as "others"
# Topics with a cumulative percentage of documents below this threshold will be grouped into an "others" topic.
# For example, if set to 0.9, topics that together account for 90% of the documents will be kept, and the rest will be grouped into "others".
others_threshold = 0.99#settings['tmo']['others_threshold']

In [39]:
# Load precomputed embeddings artifacts from dataset pipeline
embeds_base = f"{ROOT_FOLDER_PATH}/{project_folder}/{settings['metadata']['filtered_folder']}/{embeddings_folder_name}"

embeddings_array = np.load(f"{embeds_base}/embeddings.npy")
with open(f"{embeds_base}/embeddings_ids.json", "r") as f:
    embeddings_ids = json.load(f)

corpus = pd.read_csv(f"{embeds_base}/corpus.csv").reset_index(drop=True)
documents = corpus.text.to_list()

embeddings = {
    "embeddings": embeddings_array,
    "embeddings_ids": embeddings_ids,
}
print(f"Embeddings shape: {embeddings['embeddings'].shape}")

Embeddings shape: (2801, 384)

In [40]:
# verify that the number of embeddings matches the number of documents
assert(len(embeddings['embeddings']) == len(documents))

# verify that embedding and documents are in the same order as the original dataframe
id_col = 'uuid' if 'uuid' in corpus.columns else ('UT' if 'UT' in corpus.columns else None)
assert(id_col is not None), "Neither 'uuid' nor 'UT' column found in corpus.csv"
assert(corpus[id_col].astype(str).tolist() == [str(x) for x in embeddings['embeddings_ids']])

---

# Topic Modeling with BERTopic

In [41]:
from hdbscan.hdbscan_ import HDBSCAN
# Execute the topic model.
# I suggest changing the values marked with #<---
# The others are the default values and they'll work fine in most cases.
# This will take several minutes to finish.

# Initiate UMAP
umap_model = UMAP(n_neighbors=15,
                  n_components=5,
                  min_dist=0.0,
                  metric='cosine',
                  random_state=100)

if n_topics == 0:
  # Initiate topic model with HDBScan (Automatic topic selection)
  topic_model_params = HDBSCAN(min_cluster_size=min_topic_size,
                               metric='euclidean',
                               cluster_selection_method='eom',
                               prediction_data=True)
else:
  # Initiate topic model with K-means (Manual topic selection)
  topic_model_params = KMeans(n_clusters = n_topics)

# Initiate BERTopic
topic_model = BERTopic(umap_model = umap_model,
                       hdbscan_model = topic_model_params,
                       min_topic_size=min_topic_size,
                       #nr_topics=15,          #<--- Footnote 1
                       n_gram_range=(1,3),
                       language='english',
                       calculate_probabilities=True,
                       verbose=True)



# Footnote 1: This controls the number of topics we want AFTER clustering.
# Add a hashtag at the beggining to use the number of topics returned by the topic model.
# When using HDBScan nr_topics will be obtained after orphans removal, and there is no warranty that `nr_topics < HDBScan topics`.
# thus, with HDBScan `nr_topics` means N topics OR LESS.
# When using KMeans nr_topics can be used to further reduce the number of topics.
# We use the topics as returned by the topic model. So we do not need to activate it here.

In [42]:
# Compute topic model
topics, probabilities = topic_model.fit_transform(documents, embeddings['embeddings'])

2026-05-26 14:52:45,063 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-05-26 14:52:53,217 - BERTopic - Dimensionality - Completed ✓
2026-05-26 14:52:53,218 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-05-26 14:52:53,242 - BERTopic - Cluster - Completed ✓
2026-05-26 14:52:53,245 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-05-26 14:52:55,559 - BERTopic - Representation - Completed ✓

In [43]:
# Get the list of topics
# Topic = the topic number. From the largest topic.
#         "-1" is the generic topic. Genericr keywords are aggegrated here.
# Count = Documents assigned to this topic
# Name = Top 4 words of the topic based on probability
# Representation = The list of words representing this topic
# Representative_Docs = Documents assigned to this topic
tm_summary = topic_model.get_topic_info()
tm_summary

,Topic,Count,Name,Representation,Representative_Docs
0,0,108,0_science_diplomacy_science diplomacy_of science,"[science, diplomacy, science diplomacy, of sci...",[SESAME - a synchrotron light source in the Mi...
1,1,99,1_arctic_the arctic_the_of,"[arctic, the arctic, the, of, and, in, in the ...",[After Russia's invasion of Ukraine in 2022: C...
2,2,87,2_health_global health_global_and,"[health, global health, global, and, the, to, ...",[Global Health diplomacy for noncommunicable d...
3,3,84,3_water_water diplomacy_and_transboundary,"[water, water diplomacy, and, transboundary, t...",[Water-IQ matters as water conflicts mount Wat...
4,4,81,4_climate_climate change_change_the,"[climate, climate change, change, the, to, of,...",[How relevant is climate change research for c...
...,...,...,...,...,...
66,66,13,66_energy_and_brazil_technological,"[energy, and, brazil, technological, the, biof...",[Ethanol and other biofuels: Potential for U.S...
67,67,13,67_iran_sco_and_iranian,"[iran, sco, and, iranian, scientific, sanction...",[DYNAMICS OF INTERNATIONAL SCIENTIFIC COOPERAT...
68,68,12,68_protocol_montreal_the montreal_montreal pro...,"[protocol, montreal, the montreal, montreal pr...","[Mostafa Kamal Tolba, Egyptian Scientist, Envi..."
69,69,12,69_natos_natos science_the alliance_greening the,"[natos, natos science, the alliance, greening ...",[Greening the Alliance: The Diplomacy of NATO'...
70,70,10,70_pingpong_players musicians_scientists remad...,"[pingpong, players musicians, scientists remad...","[Improbable Diplomats How Ping-Pong Players, M..."

In [44]:
# Save the topic model assets
tm_folder_path = f'{ROOT_FOLDER_PATH}/{project_folder}/{settings["metadata"]["analysis_id"]}'

os.makedirs(tm_folder_path, exist_ok=True)

tm_summary.to_csv(f'{tm_folder_path}/topic_model_info.csv', index=False)

In [45]:
# Number of topics found
found_topics = max(tm_summary.Topic) + 1
found_topics

71

In [46]:
# Confirm all documents are assigned
sum(tm_summary.Count) == len(corpus)

True

In [47]:
# Get the top 10 documents for a topic
topic_model.get_representative_docs(0)

["SESAME - a synchrotron light source in the Middle East: An international research infrastructure in the making SESAME (Synchrotron-light for Experimental Science and Applications in the Middle East) is an international research centre located in Jordan. The centre was established in the late 1990s with the intention to foster scientific cooperation in a region of the world that has been torn by persistent conflicts. The project is built on the idea that science can help to overcome barriers and cultural differences within the common ground of science and research. SESAME's core ambition is to operate an international state-of-the-art synchrotron users' facility in the north of Amman that is accessible to scientists from all of its members: Cyprus, Egypt, Iran, Israel, Pakistan, Palestine, Turkey and Jordan. Accordingly, SESAME has been often praised as a paramount example of science diplomacy. Our intention for this report was to investigate a concrete international research infrastructure with a specific science diplomacy interest. What were the enabling conditions for such a project to come into being and what keeps SESAME running? What were the challenges and obstacles? How does the composition of member states play into that? How is SESAME related to (and embedded in) the global synchrotron community, academia, researchers and political actors in the region and the world? Did the science diplomacy ambition behind the project turn out to be successful and how does it affect SESAME's future? 2022 Rungius C et al.",
 'SCIENCE DIPLOMACY',
 'The Malta Conferences: Fostering International Scientific Collaborations Toward Peace in the Middle East The Malta Conferences, formally known as ""Frontiers of Science: Research and Education in the Middle East,"" have taken place biennially since 2003, at which approximately 85 scientists and science educators, including students and early-career scientists, from 15 Middle Eastern nations (Bahrain, Egypt, Iran, Iraq, Israel, Jordan, Kuwait, Lebanon, Libya, Palestinian Authority, Qatar, Saudi Arabia, Syria, Turkey, and the United Arab Emirates) meet for five days with six Nobel Laureates. The purpose of the Conferences is to provide a forum for the discussion of scientific and educational issues of importance to the region and the world that transcend geopolitical boundaries and international politics, and for the development of collaborations among the participants. The topics that are discussed include air and water quality, renewable energy sources, bio-medicinal chemistry, nanotechnology and material science, chemistry safety and security, and chemistry education at all levels. The Conferences are dedicated to the use of science diplomacy as a bridge toward peace in that troubled and very important region of the world. They feature plenary lectures by the Nobel Laureates, workshops, oral and poster presentations by participants from the Middle East, and ample time for everyone to make personal and professional connections. The result over the past decade has been the establishment of international cooperation in areas of basic and applied research that hold promise for the development of innovative products, processes, and educational resources. Prior to 2011, the Conferences were organized by a committee with representatives from the American Chemical Society (ACS), the Royal Society of Chemisry of Great Britain (RSC), the International Union of Pure and Applied Chemistry (IUPAC), and the German Chemical Society (GDCh); since that time, they have been organized by the Malta Conferences Foundation,']

In [48]:
# Print the parameters used. (For reporting)
topic_model.get_params()

{'calculate_probabilities': True,
 'ctfidf_model': ClassTfidfTransformer(),
 'embedding_model': None,
 'hdbscan_model': KMeans(n_clusters=71),
 'language': 'english',
 'low_memory': False,
 'min_topic_size': 10,
 'n_gram_range': (1, 3),
 'nr_topics': None,
 'representation_model': None,
 'seed_topic_list': None,
 'top_n_words': 10,
 'umap_model': UMAP(angular_rp_forest=True, metric='cosine', min_dist=0.0, n_components=5, n_jobs=1, random_state=100, tqdm_kwds={'bar_format': '{desc}: {percentage:3.0f}%| {bar} {n_fmt}/{total_fmt} [{elapsed}]', 'desc': 'Epochs completed', 'disable': True}),
 'vectorizer_model': CountVectorizer(ngram_range=(1, 3)),
 'verbose': True,
 'zeroshot_min_similarity': 0.7,
 'zeroshot_topic_list': None}

In [49]:
tm_params = dict(topic_model.get_params())
for key, value in tm_params.items():
    tm_params[key]=  str(value)
with open(f'{tm_folder_path}/topic_model_params.json', 'w') as f:
    json.dump(tm_params, f, ensure_ascii=False, indent=4)
    print('Done')

Done

---
# Centroids

In [50]:
import numpy as np
from sklearn.metrics.pairwise import cosine_distances

def calculate_centroid_scores(embeddings, topics, distance_metric='euclidean'):
    """
    Vectorized calculation of distance from topic centroids.
    Returns normalized scores (0-1) where 0 is the centroid and 1 is far.
    """
    embeddings = np.array(embeddings)
    topics = np.array(topics)
    unique_topics = np.unique(topics)
    
    scores = np.zeros(len(embeddings))
    
    # Calculate centroids and distances
    for topic in unique_topics:
        if topic == -1: continue # Skip outliers for centroid calculation
        
        mask = topics == topic
        topic_embeds = embeddings[mask]
        centroid = np.mean(topic_embeds, axis=0)
        
        if distance_metric == 'euclidean':
            dists = np.linalg.norm(topic_embeds - centroid, axis=1)
        else:
            dists = cosine_distances([centroid], topic_embeds)[0]
            
        # Normalize 0-1 within topic
        if len(dists) > 1 and dists.max() > dists.min():
            scores[mask] = (dists - dists.min()) / (dists.max() - dists.min())
        else:
            scores[mask] = 0 # Single document or identical distances
            
    return scores

In [51]:
# Usage with normalization:
scores = calculate_centroid_scores(embeddings['embeddings'], topics)

---
# Coordinates

In [52]:
dataset_clustering_results = topic_model.get_document_info(documents, df = corpus)
dataset_clustering_results.head()

,text,UT,uuid,Document,Topic,Name,Representation,Representative_Docs,Top_n_words,Representative_document
0,T2 Transfer of High Technology from the United...,2-s2.0-84949158352,07f20478-d824-4671-bb1d-63d4a752a7e9,T2 Transfer of High Technology from the United...,16,16_the_soviet_of_of the,"[the, soviet, of, of the, cold war, cold, war,...",[T2 Transfer of High Technology from the Unite...,the - soviet - of - of the - cold war - cold -...,True
1,"""""As if geology ended at the seashore"""": Tempo...",2-s2.0-105032555991,59bd7b4e-3c82-4060-8750-a1af76080fa5,"""""As if geology ended at the seashore"""": Tempo...",7,7_the_of_in_and,"[the, of, in, and, of the, to, de, in the, spa...",[Modernizers and technocrats. The U.S. and Spa...,the - of - in - and - of the - to - de - in th...,False
2,"""""Discrepant Expectation"""": The Delegation of ...",2-s2.0-105004398893,9cc08b63-2503-4c60-b324-8ebc3526e0d9,"""""Discrepant Expectation"""": The Delegation of ...",38,38_japan_japanese_the_in,"[japan, japanese, the, in, of, and, to, japans...",[New Migrant Organisations and the Chinese Dia...,japan - japanese - the - in - of - and - to - ...,False
3,"""""Let the devil do the rest"""": The promotion o...",2-s2.0-79960832417,f82beb11-5534-4283-ae79-60992a237a2a,"""""Let the devil do the rest"""": The promotion o...",35,35_de_the_in_la,"[de, the, in, la, of, latin, and, american, br...",[Accumulated History of the Brazilian Educatio...,de - the - in - la - of - latin - and - americ...,False
4,"'A Game, a Competition, an Instrument?': High ...",WOS:000207923100006,2364b8d6-26be-49c0-976d-0f880ff7e2c5,"'A Game, a Competition, an Instrument?': High ...",58,58_sports_sport_indonesia_the,"[sports, sport, indonesia, the, cultural, and,...","[Education as a global """"soft power"""" for sust...",sports - sport - indonesia - the - cultural - ...,False

In [53]:
from sklearn.manifold import TSNE

# 6. VISUALIZATION (Switching to t-SNE for the "Map" look)
print("Generating 2D coordinates for visualization...")

# Filter out outliers (-1) to keep the visualization clean
valid_indices = dataset_clustering_results['Topic'] != -1
valid_embeddings = np.array(embeddings['embeddings'])[valid_indices]
df_clean = dataset_clustering_results[valid_indices].reset_index(drop=True)

# --- KEY CHANGE: Use t-SNE instead of UMAP for the layout ---
# metric='cosine' is better for embeddings
# init='pca' is CRITICAL: it gives you the "ball" shape instead of random clusters
# perplexity=30-50: balances local vs global structure
tsne_model = TSNE(
    n_components=2, 
    perplexity=50,        # Higher values = more global structure
    learning_rate='auto',
    init='pca',           # This creates the global "continent" shape
    #n_iter=1000, 
    metric='cosine', 
    random_state=42, 
    n_jobs=-1             # Use all CPU cores
)

coords_2d = tsne_model.fit_transform(valid_embeddings)

# Scale coordinates to fill the frame nicely (optional but helps visualization)
# This creates that "filled frame" look
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(-100, 100))
coords_2d = scaler.fit_transform(coords_2d)

Generating 2D coordinates for visualization...

In [54]:
# Add coordinates as columns to df_clean
df_clean['x_coords_tsne'] = coords_2d[:, 0]
df_clean['y_coords_tsne'] = coords_2d[:, 1]

In [55]:
coords_2d

array([[ 37.336002 , -77.29334  ],
       [-63.716934 , -26.239523 ],
       [-10.723486 , -56.879585 ],
       ...,
       [ -0.5412593, -74.83159  ],
       [ -4.064569 , -69.097404 ],
       [ 72.20389  ,  70.97614  ]], shape=(2801, 2), dtype=float32)

---
# Save

In [56]:
# Save coords. Coords cover only the non-orphans documents.
df_clean[['uuid', 'UT', 'x_coords_tsne', 'y_coords_tsne']].to_csv(f'{tm_folder_path}/document_coords_tsne.csv', index=False)

In [57]:
# Document information. Including the topic assignation
dataset_clustering_results = topic_model.get_document_info(documents, df = corpus, metadata={"Score": scores})

# Check for orphans (Topic == -1), save and remove them
if -1 in dataset_clustering_results['Topic'].values:
    orphans = dataset_clustering_results[dataset_clustering_results['Topic'] == -1]
    orphans.to_csv(f'{tm_folder_path}/orphans.csv', index=False)
    dataset_clustering_results = dataset_clustering_results[dataset_clustering_results['Topic'] != -1]

In [58]:
# Standar format for report analysis
dataset_clustering_results = dataset_clustering_results.reset_index(drop=True)
dataset_clustering_results = dataset_clustering_results.drop(columns=['text'])
dataset_clustering_results['X_E'] = dataset_clustering_results['Score']
dataset_clustering_results['X_C'] = dataset_clustering_results['Topic'] + 1

# Assign 'level0' based on cluster coverage (90%)
cluster_counts = dataset_clustering_results['X_C'].value_counts().sort_values(ascending=False)
total_rows = len(dataset_clustering_results)
cumulative = cluster_counts.cumsum() / total_rows
main_clusters = cluster_counts.index[cumulative <= others_threshold].tolist()
dataset_clustering_results['level0'] = dataset_clustering_results['X_C'].apply(lambda x: x if x in main_clusters else 99999)
dataset_clustering_results.head()

,UT,uuid,Document,Topic,Name,Representation,Representative_Docs,Top_n_words,Representative_document,Score,X_E,X_C,level0
0,2-s2.0-84949158352,07f20478-d824-4671-bb1d-63d4a752a7e9,T2 Transfer of High Technology from the United...,16,16_the_soviet_of_of the,"[the, soviet, of, of the, cold war, cold, war,...",[T2 Transfer of High Technology from the Unite...,the - soviet - of - of the - cold war - cold -...,True,0.711503,0.711503,17,17
1,2-s2.0-105032555991,59bd7b4e-3c82-4060-8750-a1af76080fa5,"""""As if geology ended at the seashore"""": Tempo...",7,7_the_of_in_and,"[the, of, in, and, of the, to, de, in the, spa...",[Modernizers and technocrats. The U.S. and Spa...,the - of - in - and - of the - to - de - in th...,False,0.579931,0.579931,8,8
2,2-s2.0-105004398893,9cc08b63-2503-4c60-b324-8ebc3526e0d9,"""""Discrepant Expectation"""": The Delegation of ...",38,38_japan_japanese_the_in,"[japan, japanese, the, in, of, and, to, japans...",[New Migrant Organisations and the Chinese Dia...,japan - japanese - the - in - of - and - to - ...,False,0.179436,0.179436,39,39
3,2-s2.0-79960832417,f82beb11-5534-4283-ae79-60992a237a2a,"""""Let the devil do the rest"""": The promotion o...",35,35_de_the_in_la,"[de, the, in, la, of, latin, and, american, br...",[Accumulated History of the Brazilian Educatio...,de - the - in - la - of - latin - and - americ...,False,0.478367,0.478367,36,36
4,WOS:000207923100006,2364b8d6-26be-49c0-976d-0f880ff7e2c5,"'A Game, a Competition, an Instrument?': High ...",58,58_sports_sport_indonesia_the,"[sports, sport, indonesia, the, cultural, and,...","[Education as a global """"soft power"""" for sust...",sports - sport - indonesia - the - cultural - ...,False,0.576530,0.576530,59,59

In [59]:
# Standar format for report analysis
dataset_clustering_results['cl99'] = [True if x == 99999 else False for x in dataset_clustering_results['level0']]
dataset_clustering_results['cl-99'] = [True if x == 99999 else False for x in dataset_clustering_results['level0']]
dataset_clustering_results.head()

,UT,uuid,Document,Topic,Name,Representation,Representative_Docs,Top_n_words,Representative_document,Score,X_E,X_C,level0,cl99,cl-99
0,2-s2.0-84949158352,07f20478-d824-4671-bb1d-63d4a752a7e9,T2 Transfer of High Technology from the United...,16,16_the_soviet_of_of the,"[the, soviet, of, of the, cold war, cold, war,...",[T2 Transfer of High Technology from the Unite...,the - soviet - of - of the - cold war - cold -...,True,0.711503,0.711503,17,17,False,False
1,2-s2.0-105032555991,59bd7b4e-3c82-4060-8750-a1af76080fa5,"""""As if geology ended at the seashore"""": Tempo...",7,7_the_of_in_and,"[the, of, in, and, of the, to, de, in the, spa...",[Modernizers and technocrats. The U.S. and Spa...,the - of - in - and - of the - to - de - in th...,False,0.579931,0.579931,8,8,False,False
2,2-s2.0-105004398893,9cc08b63-2503-4c60-b324-8ebc3526e0d9,"""""Discrepant Expectation"""": The Delegation of ...",38,38_japan_japanese_the_in,"[japan, japanese, the, in, of, and, to, japans...",[New Migrant Organisations and the Chinese Dia...,japan - japanese - the - in - of - and - to - ...,False,0.179436,0.179436,39,39,False,False
3,2-s2.0-79960832417,f82beb11-5534-4283-ae79-60992a237a2a,"""""Let the devil do the rest"""": The promotion o...",35,35_de_the_in_la,"[de, the, in, la, of, latin, and, american, br...",[Accumulated History of the Brazilian Educatio...,de - the - in - la - of - latin - and - americ...,False,0.478367,0.478367,36,36,False,False
4,WOS:000207923100006,2364b8d6-26be-49c0-976d-0f880ff7e2c5,"'A Game, a Competition, an Instrument?': High ...",58,58_sports_sport_indonesia_the,"[sports, sport, indonesia, the, cultural, and,...","[Education as a global """"soft power"""" for sust...",sports - sport - indonesia - the - cultural - ...,False,0.576530,0.576530,59,59,False,False

In [60]:
dataset_clustering_results.level0.value_counts()

level0
1     108
2      99
3      87
4      84
5      81
     ...
64     14
65     13
67     13
68     13
66     13
Name: count, Length: 69, dtype: int64

In [61]:
# Save the dataframe
dataset_clustering_results.to_csv(f'{tm_folder_path}/dataset_minimal.csv', index=False)

In [62]:
# Save the topic model
topic_model.save(f'{tm_folder_path}/topic_model_object.pck')

2026-05-26 14:53:04,727 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

In [63]:
df_clean['uuid'].isin(dataset_clustering_results['uuid'])

0       True
1       True
2       True
3       True
4       True
        ...
2796    True
2797    True
2798    True
2799    True
2800    True
Name: uuid, Length: 2801, dtype: bool